In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
mat = np.array([[1,2,3,4,5,6,7,8],[7,8,9,10,11,12,8,9],
               [13,14,15,16,17,18,10,11],[19,20,21,22,23,24,12,13],
               [25,26,27,28,29,30,14,15],[31,32,33,34,35,36,26,27],
               [37,38,39,40,41,42,18,19],[43,44,45,46,47,48,20,21]])
fils,cols = mat.shape
#print(fils,cols)
print(mat)

[[ 1  2  3  4  5  6  7  8]
 [ 7  8  9 10 11 12  8  9]
 [13 14 15 16 17 18 10 11]
 [19 20 21 22 23 24 12 13]
 [25 26 27 28 29 30 14 15]
 [31 32 33 34 35 36 26 27]
 [37 38 39 40 41 42 18 19]
 [43 44 45 46 47 48 20 21]]


In [7]:
factor = 1/2#(25)**(1/2)/100
fils_aux = int(factor*fils)
cols_aux = int(factor*cols)
print(fils_aux,cols_aux)
fils_rand = np.sort(np.random.choice(fils, fils_aux, replace=False))
cols_rand = np.sort(np.random.choice(cols, cols_aux, replace=False))
#print(mat[fils_rand,cols_rand])
print(fils_rand,cols_rand)
mat1 = mat[fils_rand,:]#:,cols_rand]
mat1

4 4
[1 3 4 5] [0 1 6 7]


array([[ 7,  8,  9, 10, 11, 12,  8,  9],
       [19, 20, 21, 22, 23, 24, 12, 13],
       [25, 26, 27, 28, 29, 30, 14, 15],
       [31, 32, 33, 34, 35, 36, 26, 27]])

In [8]:
#mat[fils_rand,cols_rand]
mat2 = mat1[:,cols_rand]
mat2


array([[ 7,  8,  8,  9],
       [19, 20, 12, 13],
       [25, 26, 14, 15],
       [31, 32, 26, 27]])

In [9]:
print(mat2.shape,mat.shape)

(4, 4) (8, 8)


In [10]:
per_ar = np.linspace(5,100,20)#/2
#print((freq_ar/2))#.astype(int))
for pp in per_ar:
    pp_aux = pp**(0.5)
    nf = int(Nf*pp_aux)
    npp = int(Np*pp_aux)
    print(pp, pp_aux, (nf*npp)/(Nf*Np))

NameError: name 'Nf' is not defined